app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('acerca_de/', views.acerca_de, name='acerca_de'),
    path('crear_cliente/', views.crear_cliente, name='crear_cliente'),
    path('listado_clientes/', views.listado_clientes, name='listado_clientes'),
    path('editar_cliente/<int:pk>/', views.editar_cliente, name='editar_cliente'),
    path('eliminar_cliente/<int:pk>/', views.eliminar_cliente, name='eliminar_cliente'),
]

usuarios/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import UsuarioListView, UsuarioDetailView, UsuarioCreateView, UsuarioUpdateView, UsuarioDeleteView, registro, perfil, editar_perfil, CambiarContraseña, mensajeria

app_name = 'usuarios'

urlpatterns = [
    path('usuario_list/', UsuarioListView.as_view(), name='usuario-list'),
    path('<int:pk>/', UsuarioDetailView.as_view(), name='usuario-detail'),
    path('nuevo/', UsuarioCreateView.as_view(), name='usuario-create'),
    path('<int:pk>/editar/', UsuarioUpdateView.as_view(), name='usuario-update'),
    path('<int:pk>/eliminar/', UsuarioDeleteView.as_view(), name='usuario-delete'),
    path('login/', auth_views.LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('registro/', registro, name = 'registro'),
    path('perfil/', perfil, name = 'perfil'),
    path('perfil/editar/', editar_perfil, name = 'editar_perfil'),
    path('perfil/cambiar_contraseña/', CambiarContraseña.as_view(), name = 'cambiar_contraseña'),
    path('mensajeria/', mensajeria, name='mensajeria')
]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
    path('', include("usuarios.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Rodrigo Monzon</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container px-4 px-lg-5">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                                <li class="nav-item">
                                    <a class="nav-link active" href="/">Inicio</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/acerca_de">Acerca de</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/listado_clientes">Clientes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/usuario_list">Usuarios</a>
                                </li>
                                {% if user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'usuarios:mensajeria' %}">Foro</a>                        
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'usuarios:perfil' %}">
                                        Bienvenido, {{ user.username }}
                                        {% if user.infousuario.avatar %}
                                            <img src="{{ user.infousuario.avatar.url }}" alt="Avatar" style="width: 25px; height: 25px;">
                                        {% endif %}
                                    </a>                                    
                                    </a>                                    
                                </li>
                                <li class="nav-item">
                                    <form action="{% url 'usuarios:logout' %}" method='post'>
                                        {% csrf_token %}
                                    <button>Cerrar sesion</button>
                                </li>
                                {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'usuarios:login' %}">Iniciar Sesión</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'usuarios:registro' %}">Registrarse</a>
                                </li>
                                {% endif %}
                            </form>
                </div>
            </div>
        </nav>
        <header class="masthead">
            <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
                <div class="d-flex justify-content-center">
                    <div class="text-center">
                        {% block content %}
                        {% endblock content %}
                    </div>
                </div>
            </div>
        </header>
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container px-4 px-lg-5">Copyright &copy; Rodrigo Monzón</div></footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>