app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('acerca_de/', views.acerca_de, name='acerca_de'),
    path('crear_cliente/', views.crear_cliente, name='crear_cliente'),
    path('listado_clientes/', views.listado_clientes, name='listado_clientes'),
    path('editar_cliente/<int:pk>/', views.editar_cliente, name='editar_cliente'),
    path('eliminar_cliente/<int:pk>/', views.eliminar_cliente, name='eliminar_cliente'),
]

usuarios/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import UsuarioListView, UsuarioDetailView, UsuarioCreateView, UsuarioUpdateView, UsuarioDeleteView, registro, perfil, editar_perfil, CambiarContraseña, mensajeria

app_name = 'usuarios'

urlpatterns = [
    path('usuario_list/', UsuarioListView.as_view(), name='usuario-list'),
    path('<int:pk>/', UsuarioDetailView.as_view(), name='usuario-detail'),
    path('nuevo/', UsuarioCreateView.as_view(), name='usuario-create'),
    path('<int:pk>/editar/', UsuarioUpdateView.as_view(), name='usuario-update'),
    path('<int:pk>/eliminar/', UsuarioDeleteView.as_view(), name='usuario-delete'),
    path('login/', auth_views.LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('registro/', registro, name = 'registro'),
    path('perfil/', perfil, name = 'perfil'),
    path('perfil/editar/', editar_perfil, name = 'editar_perfil'),
    path('perfil/cambiar_contraseña/', CambiarContraseña.as_view(), name = 'cambiar_contraseña'),
    path('mensajeria/', mensajeria, name='mensajeria')
]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
    path('', include("usuarios.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

class Usuario(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    edad = models.IntegerField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

class InfoUsuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    
class Mensaje(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)  # Asigna el primer usuario por defecto
    contenido = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Mensaje de {self.usuario.username}"
    

usuarios/forms.py
from django import forms
from .models import Usuario, Mensaje
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['nombre', 'email', 'edad']


class RegistroDeUsuario(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Contrasenia', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repetir Contrasenia', widget=forms.PasswordInput)

    first_name = forms.CharField(label='Nombre')
    last_name = forms.CharField(label='Apellido')

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        help_texts = {
            key: ''
            for key in fields
        }


class EditarPerfil(forms.ModelForm):
    email = forms.EmailField(required=False)  # Campo de User
    avatar = forms.ImageField(required=False)  # Campo de InfoUsuario

    class Meta:
        model = User
        fields = ['email']  # Solo los campos del modelo User

    def __init__(self, *args, **kwargs):
        # Acepta la instancia de InfoUsuario como un argumento adicional
        self.info_usuario_instance = kwargs.pop('info_usuario_instance', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        user = super().save(commit=commit)
        if self.info_usuario_instance:
            avatar = self.cleaned_data.get('avatar')
            if avatar:
                self.info_usuario_instance.avatar = avatar
                if commit:
                    self.info_usuario_instance.save()
        return user

class MensajeForm(forms.ModelForm):
    class Meta:
        model = Mensaje
        fields = ['contenido']

usuarios/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from .models import Usuario, InfoUsuario, Mensaje
from .forms import UsuarioForm, RegistroDeUsuario, EditarPerfil, MensajeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import render, redirect


class UsuarioListView(ListView):
    model = Usuario
    template_name = 'usuarios/usuario_list.html'
    context_object_name = 'usuarios'

class UsuarioDetailView(LoginRequiredMixin, DetailView):
    model = Usuario
    template_name = 'usuarios/usuario_detail.html'
    context_object_name = 'usuario'

class UsuarioCreateView(LoginRequiredMixin, CreateView):
    model = Usuario
    form_class = UsuarioForm
    template_name = 'usuarios/usuario_form.html'
    success_url = reverse_lazy('usuarios:usuario-list')

class UsuarioUpdateView(LoginRequiredMixin, UpdateView):
    model = Usuario
    form_class = UsuarioForm
    template_name = 'usuarios/usuario_form.html'
    success_url = reverse_lazy('usuarios:usuario-list')

class UsuarioDeleteView(LoginRequiredMixin, DeleteView):
    model = Usuario
    template_name = 'usuarios/usuario_confirm_delete.html'
    success_url = reverse_lazy('usuarios:usuario-list')
    
def registro(request):
    formulario = RegistroDeUsuario()
    
    if request.method == "POST":
        formulario = RegistroDeUsuario(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('usuarios:login')
    
    return render(request, 'usuarios/registro.html', {'form': formulario})

def perfil(request):
    
    return render(request, 'usuarios/perfil.html', {})

from django.core.exceptions import ObjectDoesNotExist

@login_required
def editar_perfil(request):
    info_usuario, created = InfoUsuario.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        formulario = EditarPerfil(request.POST, request.FILES, instance=request.user, info_usuario_instance=info_usuario)
        if formulario.is_valid():
            formulario.save()  # Guarda los datos de User e InfoUsuario
            return redirect('usuarios:perfil')
        else:
            print("Errores del formulario:", formulario.errors)  # Depuración de errores
    else:
        formulario = EditarPerfil(instance=request.user, info_usuario_instance=info_usuario)

    return render(request, 'usuarios/editar_perfil.html', {'form': formulario})




class CambiarContraseña(LoginRequiredMixin, PasswordChangeView):
    template_name = 'usuarios/cambiar_contraseña.html'
    success_url = reverse_lazy('usuarios:perfil')
    
@login_required
def mensajeria(request):
    if request.method == "POST":
        form = MensajeForm(request.POST)
        if form.is_valid():
            mensaje = form.save(commit=False)
            mensaje.usuario = request.user  # Asigna el usuario autenticado
            mensaje.save()
            return redirect('usuarios:mensajeria')
    else:
        form = MensajeForm()

    mensajes = Mensaje.objects.all().order_by('-fecha_creacion')
    return render(request, 'usuarios/mensajeria.html', {'form': form, 'mensajes': mensajes})


usuarios/templates/usuarios/cambiar_contraseña.html
{% extends "base.html" %}

{% block content %}
<h1>Cambiar contraseña</h1>
<form action="{% url 'usuarios:cambiar_contraseña' %}" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Cambiar contraseña</button>
</form>
{% endblock %}

usuarios/templates/usuarios/editar_perfil.html
{% extends "base.html" %}
{% block title %}Editar perfil{% endblock %}
{% block content %}
<h1>Perfil de {{request.user.first_name}} {{request.user.last_name}}</h1>
<ul>
        <li>Nombre: {{request.user.first_name}}</li>
        <li>Apellido: {{request.user.last_name}}</li>        
        <li>Usuario: {{request.user.username}}</li>
        <li>Correo: {{request.user.email}}</li>
</ul>


<form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <label>Avatar Actual:</label>
            {% if request.user.infousuario.avatar %}
                <a href="{{ request.user.infousuario.avatar.url }}" target="_blank">
                    <img src="{{ request.user.infousuario.avatar.url }}" alt="Avatar" style="width: 25px; height: 25px; border-radius: 50%;">
                </a>
            {% else %}
                <p>No tienes un avatar configurado.</p>
            {% endif %}
        </div>
        <div>
            {{ form.avatar.label_tag }}:
            {{ form.avatar }}
        </div>
        <div>
            {{ form.email.label_tag }}:
            {{ form.email }}
        </div>
        <button type="submit">Guardar cambios</button>
    </form>
    
    


{% endblock %}





usuarios/templates/usuarios/login.html
{% extends "base.html" %}

{% block content %}
<h1>Iniciar Sesión</h1>
<form method="post">
    {% csrf_token %}
    <div>
        <label for="username">Usuario:</label>
        <input type="text" name="username" id="username" required>
    </div>
    <div>
        <label for="password">Contraseña:</label>
        <input type="password" name="password" id="password" required>
    </div>
    <button type="submit">Iniciar Sesión</button>
</form>
<p>No tenes cuenta? Create una aca abajo</p>
<button><a type="submit" href='/registro'>Registrarse</a></button>
{% endblock %}

usuarios/templates/usuarios/logout.html
{% extends 'base.html' %}

{% block content %}
  <h2>Has cerrado sesión correctamente</h2>
  <p>Vuelve pronto a nuestro sitio web.</p>
  <a href="{% url 'usuarios:login' %}">Iniciar sesión</a>
{% endblock %}

usuarios/templates/usuarios/mensajeria.html
{% extends "base.html" %}
{% block title %}Mensajería{% endblock %}
{% block content %}
<body>
        <h1></h1>
        <h2>Deja un mensaje:</h2>
        <form method="post" action="{% url 'usuarios:mensajeria' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Enviar</button>
            
        </form>
    
        <h2>Mensajes recientes:</h2>
        <ul>
            {% for mensaje in mensajes %}
                <li>
                    <strong>{{ mensaje.usuario.username }}</strong> dijo:
                    <p>{{ mensaje.contenido }}</p>
                    <em>{{ mensaje.fecha_creacion }}</em>
                </li>
            {% empty %}
                <li>No hay mensajes aún.</li>
            {% endfor %}
        </ul>
{% endblock %}



usuarios/templates/usuarios/perfil.html
{% extends "base.html" %}
{% block title %}Perfil{% endblock %}
{% block content %}
<h1>Perfil de {{request.user.first_name}} {{request.user.last_name}}</h1>
<ul>
        <li>Nombre: {{request.user.first_name}}</li>
        <li>Apellido: {{request.user.last_name}}</li>        
        <li>Usuario: {{request.user.username}}</li>
        <li>Correo: {{request.user.email}}</li>

        <a href={% url "usuarios:editar_perfil" %}>Editar perfil</a>
        <a href={% url "usuarios:cambiar_contraseña"%}>Cambiar contraseña</a>
</ul>


{% endblock %}

usuarios/templates/usuarios/registro.html
{% extends "base.html" %}

{% block content %}
<h1>Registrar administradores</h1>
<form action="{% url 'usuarios:registro' %}" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Registrarse</button>
</form>
{% endblock %}

usuarios/templates/usuarios/usuario_confirm_delete.html
{% extends "base.html" %}
{% block title %}Eliminar Usuario{% endblock %}
{% block content %}
<p>¿Estás seguro de que deseas eliminar a {{ object.nombre }}?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Sí, eliminar</button>
</form>
<a href="{% url 'usuarios:usuario-list' %}">Cancelar</a>
{% endblock %}

usuarios/templates/usuarios/usuario_detail.html
{% extends "base.html" %}
{% block title %}Detalles del Usuario{% endblock %}
{% block content %}
<p>Nombre: {{ usuario.nombre }}</p>
<p>Email: {{ usuario.email }}</p>
<p>Edad: {{ usuario.edad }}</p>
<a href="{% url 'usuarios:usuario-update' usuario.pk %}">Editar</a>
<a href="{% url 'usuarios:usuario-delete' usuario.pk %}">Eliminar</a>
<a href="{% url 'usuarios:usuario-list' %}">Volver</a>
{% endblock %}

usuarios/templates/usuarios/usuario_form.html
{% extends "base.html" %}
{% block title %} {{ view.object.pk|yesno:"Editar Usuario,Nuevo Usuario" }} {% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
<a href="{% url 'usuarios:usuario-list' %}">Cancelar</a>
{% endblock %}

usuarios/templates/usuarios/usuario_list.html
{% extends "base.html" %}
{% block title %} Lista de usuarios{% endblock %}
{% block content %}

<a href="{% url 'usuarios:usuario-create' %}">Crear Usuario</a>
<ul>
    {% for usuario in usuarios %}
        <li>
            <a href="{% url 'usuarios:usuario-detail' usuario.pk %}">{{ usuario.nombre }}</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}